[package]
name = "sqlxtinker"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.3", features = [ "all-databases", "runtime-tokio-native-tls" ] }
tokio = { version = "1", features = ["full"] }
druid = "0.8.3"
